language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install pylint

script:
    - "./build.sh"
    - pylint $(find src/ -name '*.py')

defore_deploy:
    - "./build.sh --deploy"

deploy:
    provider: releases
    api_key:
        secure: "jMMewyhho7trhGGjjRGUVaHKaXq8U5oDS4SiUV3ye5NWOfTZv6Rx6WfrJ5T3uNWmB+0Sw/JncaVeBlRxcclgtgOvdwvsoDS+sglvcBn40/VHZEHLxx1fpNdShDF6cvcUzVdrOoFVYdUvop4NTNoFiprIX/Qs8zWGZ6rhKiqKvhwyF3PawH5QRYjqKbHy7RDWbqqyMqaV5OxSZanYPbVgXTYk0zSUiKG7PyPUlnu6Xnpa7YAKdhXmixzAQpY7fcR4r+Y3+a+suxWTON1phZDYYWwJXT2vyIIC4yNbf1DECINx36OlCxIg9twozCr1BoDbjisXTjvZ/4mVedGnEhOhsIf7EJ5pe21KJAv4dZDR0wNjX/+ySRdwfIrU1oYi+OW7lbgmsCCIqIA0KHifO5hPvwlWuSD9aSu3xKoEdEcJbvERJsdzNemz2SldjVJc6om5sNzPsQD/1IGEew8+nV0o+tkedBtd99Oppji4ijTfQ4uFo7SSsF82eLZDHLz99KYt7O16AxLMr6wJMa9vDVXQut4FVamraoEV32M5562ykgcKOecduHkzkd+Q/Q1Ot/h1XoajwYb/C7hH8m96QQ6EKaI1GpzpIcqh/sQ6S+74ysNd4Uan4Nim3cME2JDfjWE0LA/oYNXSiMZ69S6u+qJyoHwXHXgscBdoCj12RtTxzW0="
    file: "dist/ControlAnySim.zip"
    skip_cleanup: true
    draft: true
    on:
        tags: true
        repo: TitanNano/TS4ControlAnySim
