language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install pylint

script:
    - "./build.sh"
    - pylint $(find src/ -name '*.py')

defore_deploy:
    - "./build.sh --deploy"

deploy:
    provider: releases
    api_key:
        secure: "$GITHUB_ACCESS_TOKEN"
    file: "dist/ControlAnySim.zip"
    skip_cleanup: true
    draft: true
    on:
        tags: true
        repo: TitanNano/TS4ControlAnySim
